/* THIS FILE WAS GENERATED BY versionup.ps1 */
/* DO NOT CHANGE MANUALLY !!                */
#pragma once

#define MAJOR 0
#define MINOR 1
#define PATCH 1
#define BUILD 0

#define SEMVER "0.1.1"
#define LEGAL_COPYRIGHT "Copyright 2025 Yasumasa Suenaga"
