param(
    [string]$version
)

$solutiondir = $PSScriptRoot


function Generate-Version-Header-File([int]$major, [int]$minor, [int]$patch, [int]$build, [string]$semver){
  $copyright_year = Get-Date -Format 'yyyy'
  $contents = @"
/* THIS FILE WAS GENERATED BY versionup.ps1 */
/* DO NOT CHANGE MANUALLY !!                */
#pragma once

#define MAJOR $major
#define MINOR $minor
#define PATCH $patch
#define BUILD $build

#define SEMVER "$semver"
#define LEGAL_COPYRIGHT "Copyright $copyright_year Yasumasa Suenaga"
"@

  Set-Content -Path "$solutiondir\version.h" -Encoding UTF8 -Value $contents
}


function Update-Installer-Version([int]$major, [int]$minor, [int]$patch, [int]$build, [string]$semver){
  $source_file = "$solutiondir\installer\Product.wxs"
  $xml = [xml]::new()
  $xml.Load($source_file)
  $xml.Wix.Product.Version = "$major.$minor.$patch.$build"
  $xml.Save($source_file)

  $source_file = "$solutiondir\installer\installer.wixproj"
  $xml = [xml]::new()
  $xml.Load($source_file)
  $outputNameNode = $xml.SelectSingleNode("//*[local-name()='OutputName']")
  Write-Output $outputNameNode
  $outputNameNode.InnerText = "hvcp-$semver"
  $xml.Save($source_file)
}


$valid_version = $version -match '^(\d+)\.(\d+)\.(\d+)(\.(\d+))?$'
if(!$valid_version){
  Write-Output 'Invalid version string'
  return
}

[int]$major = $Matches.1
[int]$minor = $Matches.2
[int]$patch = $Matches.3
[int]$build = $Matches.5 ?? 0

$semver = $build -eq 0 ? "$major.$minor.$patch" : "$major.$minor.$patch+$build"
Write-Output "Version: $semver"

Generate-Version-Header-File $major $minor $patch $build $semver
Update-Installer-Version $major $minor $patch $build $semver