param(
    [string]$version
)

$solutiondir = $PSScriptRoot


function Generate-Version-Header-File([int]$major, [int]$minor, [int]$patch, [int]$build, [string]$semver){
  $copyright_year = Get-Date -Format 'yyyy'
  $contents = @"
/* THIS FILE WAS GENERATED BY versionup.ps1 */
/* DO NOT CHANGE MANUALLY !!                */
#pragma once

#define MAJOR $major
#define MINOR $minor
#define PATCH $patch
#define BUILD $build

#define SEMVER "$semver"
#define LEGAL_COPYRIGHT "Copyright $copyright_year Yasumasa Suenaga"
"@

  Set-Content -Path "$solutiondir\version.h" -Encoding UTF8 -Value $contents
}


function Update-Installer-Version([int]$major, [int]$minor, [int]$patch, [int]$build, [string]$semver){
  $source_file = "$solutiondir\installer\Product.wxs"
  $xml = [xml]::new()
  $xml.Load($source_file)
  $xml.Wix.Product.Version = "$major.$minor.$patch.$build"
  $xml.Save($source_file)

  $source_file = "$solutiondir\installer\installer.wixproj"
  $xml = [xml]::new()
  $xml.Load($source_file)
  $outputNameNode = $xml.SelectSingleNode("//*[local-name()='OutputName']")
  $outputNameNode.InnerText = "hvcp-$semver"
  $xml.Save($source_file)
}


function Update-SPEC-Version([string]$semver){
  $spec_file = "$solutiondir\rpm\hvcp.spec"
  $content = Get-Content $spec_file -Encoding UTF8
  $updatedContent = @()

  foreach($line in $content){
    if($line -match '^Version:\s+'){
      $updatedContent += "Version: $semver"
    }
    elseif($line -match '^Copyright'){
      $copyright_year = Get-Date -Format 'yyyy'
      $updatedContent += "Copyright $copyright_year Yasumasa Suenaga"
    }
    elseif($line -match "^%changelog$"){
      $currentDate = (Get-Date).ToString("ddd MMM dd yyyy", [System.Globalization.CultureInfo]::InvariantCulture)
      $git_username = (& git config user.name).Trim()
      $git_useremail = (& git config user.email).Trim()

      $updatedContent += $line
      $updatedContent += "* $currentDate $git_username <$git_useremail>"
      $updatedContent += "- Up to $semver"
    }
    else{
      $updatedContent += $line
    }
  }

  $updatedContentText = $updatedContent -join "`n"
  $utf8NoBom = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllText($spec_file, $updatedContentText, $utf8NoBom)
}


$valid_version = $version -match '^(\d+)\.(\d+)\.(\d+)(\.(\d+))?$'
if(!$valid_version){
  Write-Output 'Invalid version string'
  return
}

[int]$major = $Matches.1
[int]$minor = $Matches.2
[int]$patch = $Matches.3
[int]$build = $Matches.5 ?? 0

$semver = $build -eq 0 ? "$major.$minor.$patch" : "$major.$minor.$patch+$build"
Write-Output "Version: $semver"

Generate-Version-Header-File $major $minor $patch $build $semver
Update-Installer-Version $major $minor $patch $build $semver
Update-SPEC-Version $semver