name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build
        run: msbuild hvcp.sln /p:Configuration=Debug /p:Platform=x64 /t:cli

  build-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
        working-directory: linux
